import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quarta Entrega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header className="bg-gray-700 text-white">
        <h2>MEUS PRODUTOS</h2>
              <ul>
                <li><Link href="/">HOME</Link></li>
                <li><Link href="/Produtos/calca">CALÇA</Link></li>
                <li><Link href="/Produtos/meia">MEIA</Link></li>
                <li><Link href="/Produtos/camisa">CAMISA</Link></li>
                <li><Link href="/Produtos/tenis">TÊNIS</Link></li>
              </ul>
        </header>


        {children}</body>
    </html>
  )
}
